# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PaperUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('library', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='user_id',
        ),
        migrations.AddField(
            model_name='paperuserrelation',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanity.Paper'),
        ),
        migrations.AddField(
            model_name='paperuserrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanity.PaperTag'),
        ),
        migrations.AddField(
            model_name='paperuserrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ManyToManyField(through='sanity.PaperUserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
