# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0002_auto_20180105_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperuserrelation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paperuserrelation',
            name='library',
            field=models.BooleanField(default=False),
        ),
    ]
