# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0004_auto_20180105_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='user',
            new_name='users',
        ),
    ]
