# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0005_auto_20180105_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='first_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sanity.Version'),
        ),
        migrations.AddField(
            model_name='paper',
            name='last_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sanity.Version'),
        ),
    ]
