# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0006_auto_20180108_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='first_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sanity.Version'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='last_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sanity.Version'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(),
        ),
    ]
