# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0007_auto_20180115_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperIndex',
            fields=[
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sanity.Paper')),
                ('date_last', models.IntegerField(db_index=True, null=True, unique=True)),
                ('date_first', models.IntegerField(db_index=True, null=True, unique=True)),
                ('library', models.IntegerField(db_index=True, null=True)),
                ('library_last_y', models.IntegerField(db_index=True, null=True)),
                ('library_last_m', models.IntegerField(db_index=True, null=True)),
                ('library_last_w', models.IntegerField(db_index=True, null=True)),
                ('library_last_d', models.IntegerField(db_index=True, null=True)),
                ('tweet', models.IntegerField(db_index=True, null=True)),
                ('tweet_last_y', models.IntegerField(db_index=True, null=True)),
                ('tweet_last_m', models.IntegerField(db_index=True, null=True)),
                ('tweet_last_w', models.IntegerField(db_index=True, null=True)),
                ('tweet_last_d', models.IntegerField(db_index=True, null=True)),
            ],
        ),
    ]
