# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0008_paperindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-user_follower']},
        ),
    ]
